# Generated by Django 3.0.6 on 2021-09-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
    ]
